name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: shin-102
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Casablanca

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_analysis_timeout: 15

          plugin_habits: yes
          plugin_habits_from: 100 
          plugin_habits_days: 7    
          plugin_habits_facts: no  
          plugin_habits_charts: no 

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          plugin_repositories: yes
          plugin_repositories_featured: 3

          plugin_lines: yes

          config_display: large
          config_padding: 0, 8 + 11%
